name: Tests

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install libdbus-1-dev libasound2-dev libwebkit2gtk-4.0-dev appmenu-gtk3-module libgtk-3-dev
      - name: Setup
        run: yarn
      - name: Build
        run: yarn run build
      - name: Run tests
        run: yarn run all-tests
